import type { PullData } from "./types";

/** A finished-enough log so a new founder can see what “real” looks like, then wipe it. */
export const EXAMPLE: PullData = {
  company: "Rate desk",
  line: "We chase signed rate confirmations for small freight brokers.",
  metric: "brokers who sent another load this week",
  people: [
    { id: "p1", name: "Luis Ortega", role: "ops lead at a 12-person freight broker", reach: "LinkedIn, mutual in logistics Slack", status: "tried" },
    { id: "p2", name: "Priya Shah", role: "owner, regional brokerage", reach: "warm intro from Luis", status: "tried" },
    { id: "p3", name: "Ben Carter", role: "night dispatcher", reach: "r/FreightBrokers", status: "talked" },
    { id: "p4", name: "Helen Cho", role: "carrier sales at a 30-person desk", reach: "cold email after a podcast", status: "talked" },
    { id: "p5", name: "Marcus Adeyemi", role: "broker who still uses a shared inbox", reach: "friend of Priya", status: "to-contact" },
    { id: "p6", name: "Dana Ruiz", role: "ops at a produce broker", reach: "local trucking meetup", status: "gone" },
  ],
  talks: [
    {
      id: "t1",
      personId: "p1",
      at: "2026-09-02",
      pitched: false,
      lastTime: "Tuesday a shipper swore the rate was $2.10 and the signed confirmation was in someone else's inbox. Luis spent 40 minutes reconstructing it before the driver would roll.",
      paysToday: "A coordinator, about $18 an hour, plus late trucks",
      quote: "I don't need another TMS. I need the signed rate in my hand before the driver asks.",
      pain: "chasing signed rate confirmations",
      commitment: "data",
    },
    {
      id: "t2",
      personId: "p2",
      at: "2026-09-04",
      pitched: false,
      lastTime: "Last Thursday two loads sat because the rate con was a photo in a group text. She forwarded the whole thread and asked if someone could just pull the number out.",
      paysToday: "Her own nights, and a $200 lumper fee when the truck waited",
      quote: "If you can put the signed rate on one page before pickup, I will send you the next ten loads.",
      pain: "chasing signed rate confirmations",
      commitment: "another-call",
    },
    {
      id: "t3",
      personId: "p3",
      at: "2026-09-06",
      pitched: false,
      lastTime: "Saturday shift. Driver called from the dock. Ben had the rate in email, not on the paperwork the warehouse wanted. He retyped it from three messages.",
      paysToday: "Overtime and missed pickups",
      quote: "Every Saturday it's the same hunt for the signed rate.",
      pain: "chasing signed rate confirmations",
      commitment: "intro",
    },
    {
      id: "t4",
      personId: "p4",
      at: "2026-09-08",
      pitched: true,
      lastTime: "She said the tools they use are fine.",
      paysToday: "",
      quote: "Sounds cool, send me the deck.",
      pain: "AI for logistics",
      commitment: "none",
    },
    {
      id: "t5",
      personId: "p6",
      at: "2026-09-09",
      pitched: false,
      lastTime: "She described a different problem: finding refrigerated trucks in July, not paperwork.",
      paysToday: "A load board subscription",
      quote: "My problem is trucks, not paper.",
      pain: "finding reefers in season",
      commitment: "none",
    },
  ],
  manual: [
    {
      id: "m1",
      personId: "p1",
      at: "2026-09-11",
      what: "Took Luis's last 8 email threads and returned a one-page rate with the signature, the number, and the pickup window.",
      hours: 3,
      cameBack: true,
    },
    {
      id: "m2",
      personId: "p2",
      at: "2026-09-14",
      what: "Did the same for two of Priya's loads. She said thanks and did not send the next ten.",
      hours: 2,
      cameBack: false,
    },
  ],
  weeks: [
    { id: "w1", weekOf: "2026-09-08", value: 1, note: "Luis sent a second batch." },
    { id: "w2", weekOf: "2026-09-15", value: 1, note: "Still only Luis." },
  ],
};
